# Generated by Django 5.1.7 on 2025-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
            ],
        ),
    ]
