# Generated by Django 5.1.7 on 2025-04-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='senha',
            field=models.CharField(default='senha123', max_length=12),
        ),
    ]
