# Generated by Django 5.1.7 on 2025-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='sobrenome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
