# Generated by Django 5.1.7 on 2025-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_sobrenome_alter_colaborador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='senha',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='sobrenome',
            field=models.CharField(default='desconhecido', max_length=50),
            preserve_default=False,
        ),
    ]
