# Generated by Django 5.1.7 on 2025-04-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_colaborador_senha_alter_colaborador_sobrenome'),
        ('contas', '0001_initial'),
        ('treinamentos', '0002_remove_treinamento_colaborador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='senha',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default='1', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='contas.conta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TreinamentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_validade_treinamento', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamentos.treinamento')),
            ],
        ),
    ]
