# Generated by Django 5.1.7 on 2025-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_remove_colaborador_senha_colaborador_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
