# Generated by Django 5.1.7 on 2025-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_colaborador_treinamentos'),
        ('treinamentos', '0006_rename_olaboradores_treinamento_colaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='treinamentos',
            field=models.ManyToManyField(blank=True, related_name='colaboradores_inscritos', through='colaboradores.TreinamentoColaborador', to='treinamentos.treinamento'),
        ),
    ]
