# Generated by Django 5.1.7 on 2025-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0009_alter_colaborador_treinamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamentocolaborador',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('valido', 'Válido'), ('vencido', 'Vencido')], default='pendente', max_length=10),
        ),
    ]
