# Generated by Django 5.1.7 on 2025-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0013_cargo_alter_colaborador_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
