# Generated by Django 5.2 on 2025-06-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0014_alter_colaborador_cargo_delete_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('gerencia', 'Gerência'), ('rh', 'RH'), ('assistente_administrativo', 'Assistente Administrativo'), ('analista_financeiro', 'Analista Financeiro'), ('contador', 'Contador'), ('analista_rh', 'Analista de RH'), ('tratorista', 'Tratorista'), ('operador_maquinas', 'Operador de Máquinas Agrícolas'), ('auxiliar_campo', 'Auxiliar de Campo'), ('encarregado_producao', 'Encarregado de Produção'), ('supervisor_agricola', 'Supervisor Agrícola'), ('engenheiro_agronomo', 'Engenheiro Agrônomo'), ('zootecnista', 'Zootecnista'), ('veterinario', 'Veterinário'), ('motorista', 'Motorista'), ('almoxarife', 'Almoxarife'), ('operador_armazem', 'Operador de Armazém'), ('supervisor_logistica', 'Supervisor de Logística'), ('representante_comercial', 'Representante Comercial'), ('consultor_tecnico_vendas', 'Consultor Técnico de Vendas'), ('coordenador_vendas', 'Coordenador de Vendas'), ('assistente_comercial', 'Assistente Comercial'), ('mecanico_agricola', 'Mecânico Agrícola'), ('eletricista', 'Eletricista'), ('encanador', 'Encanador'), ('supervisor_manutencao', 'Supervisor de Manutenção'), ('tecnico_suporte', 'Técnico de Suporte'), ('analista_sistemas', 'Analista de Sistemas'), ('desenvolvedor_software', 'Desenvolvedor de Software')], max_length=100),
        ),
    ]
