# Generated by Django 5.1.7 on 2025-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='treinamento',
            name='prazo_validade',
            field=models.IntegerField(default=1.0, help_text='Validade do treinamento em meses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('naorealizado', 'Não Realizado'), ('emandamento', 'Em Andamento'), ('concluido', 'Concluído')], default='naorealizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
