# Generated by Django 5.1.7 on 2025-04-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0007_alter_colaborador_usuario'),
        ('treinamentos', '0002_remove_treinamento_colaborador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='colaborador',
            field=models.ManyToManyField(related_name='treinamentos', to='colaboradores.colaborador'),
        ),
    ]
