# Generated by Django 5.1.7 on 2025-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0007_alter_colaborador_usuario'),
        ('treinamentos', '0003_treinamento_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='treinamento',
            name='colaboradores',
            field=models.ManyToManyField(through='colaboradores.TreinamentoColaborador', to='colaboradores.colaborador'),
        ),
    ]
