# Generated by Django 5.1.7 on 2025-04-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_colaborador_treinamentos'),
        ('treinamentos', '0004_remove_treinamento_colaborador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='colaboradores',
        ),
        migrations.AddField(
            model_name='treinamento',
            name='olaboradores',
            field=models.ManyToManyField(related_name='treinamentos_associados', through='colaboradores.TreinamentoColaborador', to='colaboradores.colaborador'),
        ),
    ]
