# Generated by Django 5.1.7 on 2025-04-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0005_remove_treinamento_colaboradores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinamento',
            old_name='olaboradores',
            new_name='colaboradores',
        ),
    ]
