# Generated by Django 5.2 on 2025-04-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0006_rename_olaboradores_treinamento_colaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('naorealizado', 'Não Realizado'), ('emandamento', 'Em aplicação'), ('concluido', 'Concluído')], default='naorealizado', max_length=20),
        ),
    ]
